name: Test script 

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  notebook_update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install dependencies [Operating System]
        run: sudo apt install espeak
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: python -m pip install --upgrade pip -r src/config/requirements.txt
      - name: Test Build and Version
        run: pytest tests/
      - name: Run Tox test
        # Run tox using the version of Python in `PATH`
        run: tox